Repository Azure/terraform-azurerm-avm-template, pull requests merged in 2024-05, with the labels that each got.

#110 Update CODEOWNERS
  .github/CODEOWNERS
Labels: Needs: Triage :mag:

#115 feat: remove jsonls and simplify
  .github/actions/e2e-getexamples/action.yml
Labels: enhancement, Needs: Triage :mag:

#114 feat: container run as current user
  avm
  locals.tf
  variables.tf
Labels: enhancement

#119 Add support for linting sub-modules
  .gitignore
  modules/.terraform-docs.yml
Labels: enhancement
